#ifndef CONFIG_CUH                                                                      
#define CONFIG_CUH                                                                      
/*****************************                                                          
 * Autogenerated by config.py                                                           
 *                                                                                      
 * DO NOT MODIFY!                                                                       
 ****************************/                                                          
                                                                                        
#include <string>                                                                       
                                                                                        
#include "real.cuh"                                                                     
                                                                                        
// Device number                                                                        
const int devNumber = 0;                                                     
                                                                                        
// Multicomponent                                                                       
#define MULTICOMPONENT                                              
                                                                                        
// Number of point for side                                                             
constexpr int N = 401;                                                                  
                                                                                        
#ifdef DOUBLE_PRECISION                                                                 
constexpr int blockSizeX = 512;                                                         
#else                                                                                   
constexpr int blockSizeX = 1024;                                                        
#endif                                                                                  
                                                                                        
constexpr int gridSizeX = (int)((N*N)/blockSizeX + 1);                                  
constexpr real dx = 0.020000000000000018;                                                               
                                                                                        
constexpr int default_relaxation_step_number = 10;        
                                                                                        
#endif // CONFIG_CUH                                                                    
